version: '3.9'

services:
  v2gdecoder-din70121:
    build: ./V2Gdecoder-din70121
    ports:
      - "9081:9000"
    networks:
      v2gweb:
        ipv4_address: 172.16.0.2
  
  # v2gdecoder-iso15118:
  #   build: ./V2Gdecoder-iso15118
  #   ports:
  #     - "9082:9000"
  #   networks:
  #     v2gweb:
  #       ipv4_address: 172.16.0.4

  
  v2gwebserver:
    build: ./webserver/
    ports:
      - "1234:80"
    depends_on:
      - v2gdecoder
    networks:
      v2gweb:
        ipv4_address: 172.16.0.3

networks:
  v2gweb:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.0.0/24